server:
  port: 7071
spring:
  application:
    name: copyright-registration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/copyright_uk
    username: root
    password: "!!June@2023"
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

